"use client";

import { Bot } from "lucide-react";
import { useThemePreview } from "@/hooks/use-theme-preview";
import { cn } from "@/lib/cn";

interface AIGeneratedBadgeProps {
  className?: string;
  model?: string;
  generatedAt?: string;
}

export function AIGeneratedBadge({ className, model, generatedAt }: AIGeneratedBadgeProps) {
  const { isIntercom } = useThemePreview();

  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 type-label",
        isIntercom
          ? "border border-[#ff5600]/20 bg-[#ff5600]/10 text-[#ff5600]"
          : "rounded-sm bg-muted text-muted-foreground",
        className
      )}
      title={model ? `Generated by ${model}${generatedAt ? ` at ${generatedAt}` : ""}` : "AI-generated"}
    >
      <Bot className="h-3 w-3" />
      AI-generated
    </span>
  );
}
