import { Bot } from "lucide-react";
import { cn } from "@/lib/cn";

interface AIGeneratedBadgeProps {
  className?: string;
  model?: string;
  generatedAt?: string;
}

export function AIGeneratedBadge({ className, model, generatedAt }: AIGeneratedBadgeProps) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-sm bg-muted px-1.5 py-0.5 text-xs text-muted-foreground",
        className
      )}
      title={model ? `Generated by ${model}${generatedAt ? ` at ${generatedAt}` : ""}` : "AI-generated"}
    >
      <Bot className="h-3 w-3" />
      AI-generated
    </span>
  );
}
