export const designTokens = {
  color: {
    background: "hsl(var(--background))",
    foreground: "hsl(var(--foreground))",
    primary: "hsl(var(--primary))",
    primaryForeground: "hsl(var(--primary-foreground))",
    secondary: "hsl(var(--secondary))",
    secondaryForeground: "hsl(var(--secondary-foreground))",
    accent: "hsl(var(--accent))",
    accentForeground: "hsl(var(--accent-foreground))",
    muted: "hsl(var(--muted))",
    mutedForeground: "hsl(var(--muted-foreground))",
    card: "hsl(var(--card))",
    cardForeground: "hsl(var(--card-foreground))",
    popover: "hsl(var(--popover))",
    popoverForeground: "hsl(var(--popover-foreground))",
    border: "hsl(var(--border))",
    input: "hsl(var(--input))",
    ring: "hsl(var(--ring))",
    destructive: "hsl(var(--destructive))",
    destructiveForeground: "hsl(var(--destructive-foreground))",
    success: "hsl(var(--success))",
    successForeground: "hsl(var(--success-foreground))",
    warning: "hsl(var(--warning))",
    warningForeground: "hsl(var(--warning-foreground))",
    live: "hsl(var(--live))",
    liveForeground: "hsl(var(--live-foreground))",
    nudge: "hsl(var(--nudge))",
    nudgeForeground: "hsl(var(--nudge-foreground))",
  },
  radius: {
    base: "var(--radius)",
    sm: "calc(var(--radius) - 4px)",
    md: "calc(var(--radius) - 2px)",
    lg: "var(--radius)",
    xl: "calc(var(--radius) + 4px)",
    "2xl": "calc(var(--radius) + 8px)",
  },
  shadow: {
    card: "var(--shadow-card)",
    xs: "var(--shadow-soft-xs)",
    sm: "var(--shadow-soft-sm)",
    md: "var(--shadow-soft-md)",
    lg: "var(--shadow-soft-lg)",
  },
  typography: {
    sans: "var(--font-sans)",
    mono: "var(--font-mono)",
    display: "var(--text-display)",
    headline: "var(--text-headline)",
    title: "var(--text-title)",
    body: "var(--text-body)",
    bodySm: "var(--text-body-sm)",
    label: "var(--text-label)",
    caption: "var(--text-caption)",
  },
} as const;

export type DesignTokens = typeof designTokens;
