"""Filter transcript tokens to industry-relevant, actionable terms (not fillers)."""

from __future__ import annotations

import re
from typing import Dict, Iterable, List, Set

_STOPWORDS: Set[str] = {
    "a",
    "an",
    "the",
    "and",
    "or",
    "but",
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "must",
    "can",
    "we",
    "you",
    "they",
    "it",
    "this",
    "that",
    "these",
    "those",
    "i",
    "he",
    "she",
    "so",
    "if",
    "as",
    "with",
    "from",
    "by",
    "about",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "up",
    "down",
    "out",
    "off",
    "over",
    "under",
    "again",
    "then",
    "once",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "each",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "than",
    "too",
    "very",
    "just",
    "also",
    "now",
    "our",
    "your",
    "their",
    "what",
    "which",
    "who",
    "whom",
    "yeah",
    "yes",
    "ok",
    "okay",
    "um",
    "uh",
    "like",
    "know",
    "think",
    "going",
    "get",
    "got",
    "really",
    "well",
    "right",
    "actually",
    "basically",
    "literally",
    "honestly",
    "anyway",
    "stuff",
    "things",
    "gonna",
    "wanna",
    "gotta",
    "thanks",
    "please",
    "sorry",
    "hello",
    "hey",
    "hi",
    "see",
    "look",
    "tell",
    "said",
    "say",
    "says",
    "talk",
    "talking",
    "ask",
    "asked",
    "asking",
    "want",
    "wanted",
    "need",
    "needed",
    "make",
    "made",
    "let",
    "put",
    "take",
    "took",
    "come",
    "came",
    "go",
    "went",
    "lot",
    "lots",
    "bit",
    "little",
    "big",
    "today",
    "tomorrow",
    "yesterday",
    "week",
    "month",
    "year",
    "time",
    "times",
    "day",
    "days",
    "people",
    "person",
    "team",
    "teams",
    "company",
    "companies",
    "business",
    "work",
    "working",
    "help",
    "helps",
    "helped",
}

_WEAK_TERMS: Set[str] = {
    "data",
    "system",
    "systems",
    "process",
    "processes",
    "solution",
    "solutions",
    "service",
    "services",
    "project",
    "projects",
    "issue",
    "issues",
    "problem",
    "problems",
    "plan",
    "plans",
    "call",
    "meeting",
    "update",
    "updates",
}

# Tech / franchise / enterprise discovery vocabulary (boost or allow)
_INDUSTRY_TERMS: Set[str] = {
    "api",
    "apis",
    "integration",
    "integrations",
    "pos",
    "franchise",
    "franchisee",
    "franchisees",
    "compliance",
    "audit",
    "audits",
    "platform",
    "orchestration",
    "agent",
    "agents",
    "ai",
    "ml",
    "saas",
    "erp",
    "crm",
    "salesforce",
    "sap",
    "servicenow",
    "soc2",
    "gdpr",
    "rfp",
    "pilot",
    "poc",
    "roi",
    "kpi",
    "board",
    "cfo",
    "cto",
    "cio",
    "vp",
    "architecture",
    "multi-tenant",
    "multitenant",
    "kubernetes",
    "cloud",
    "aws",
    "azure",
    "gcp",
    "security",
    "regulatory",
    "esg",
    "budget",
    "timeline",
    "deadline",
    "go-live",
    "proposal",
    "vendor",
    "competitor",
    "incumbent",
    "procurement",
    "stakeholder",
    "stakeholders",
    "q1",
    "q2",
    "q3",
    "q4",
}

_MONEY_PATTERN = re.compile(
    r"\$[\d,.]+[kmb]?|\b\d+(?:\.\d+)?\s*(?:million|billion|thousand|k|m|b)\b",
    re.I,
)
_FISCAL_PATTERN = re.compile(r"\bq[1-4]\b|\bfy\d{2,4}\b", re.I)


def normalize_term(term: str) -> str:
    return term.lower().strip().strip("'-_")


def is_salient_term(term: str) -> bool:
    t = normalize_term(term)
    if len(t) < 3:
        return False
    if t in _STOPWORDS or t in _WEAK_TERMS:
        return False
    if t.isdigit():
        return False
    if t in _INDUSTRY_TERMS:
        return True
    # Allow longer tokens (likely product/company names) and hyphenated tech terms
    if len(t) >= 5 and re.match(r"^[a-z][a-z0-9-]*$", t):
        return True
    return False


def extract_salient_phrases(text: str) -> List[str]:
    """Pull high-signal phrases from raw transcript (money, fiscal periods)."""
    lower = text.lower()
    found: List[str] = []
    for pat in (_MONEY_PATTERN, _FISCAL_PATTERN):
        for m in pat.finditer(lower):
            phrase = m.group(0).strip()
            if phrase and phrase not in found:
                found.append(phrase)
    return found[:5]


def filter_salient_terms(terms: Iterable[str]) -> List[str]:
    seen: Set[str] = set()
    out: List[str] = []
    for term in terms:
        t = normalize_term(term)
        if not is_salient_term(t) or t in seen:
            continue
        seen.add(t)
        out.append(t)
    return out
