"use client";

import { Workflow } from "lucide-react";
import { useThemePreview } from "@/hooks/use-theme-preview";
import { cn } from "@/lib/cn";

interface WorkflowAgentBadgeProps {
  className?: string;
}

/** Labels content produced by PRE-DC Workflow on the Pre-DC screen. */
export function WorkflowAgentBadge({ className }: WorkflowAgentBadgeProps) {
  const { isIntercom } = useThemePreview();

  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 text-xs font-medium",
        isIntercom
          ? "border border-[#ff5600]/20 bg-[#ff5600]/10 text-[#ff5600]"
          : "rounded-sm bg-primary/10 text-primary",
        className
      )}
      title="Generated by PRE-DC Workflow"
    >
      <Workflow className="h-3 w-3 shrink-0" />
      PRE-DC Workflow
    </span>
  );
}
