"use client";

import { Workflow } from "lucide-react";
import { cn } from "@/lib/cn";

interface WorkflowAgentBadgeProps {
  className?: string;
}

/** Labels content produced by the Workflow agent on the Pre-DC screen. */
export function WorkflowAgentBadge({ className }: WorkflowAgentBadgeProps) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-sm bg-primary/10 px-1.5 py-0.5 text-xs font-medium text-primary",
        className
      )}
      title="Generated by Workflow Agent"
    >
      <Workflow className="h-3 w-3" />
      Workflow
    </span>
  );
}
