/** Re-export brief shapes from shared types (no mock data). */
export type {
  CallBrief,
  PostCallReview,
  BriefResearchSection,
  PostDcBriefPreview,
  HypothesizedPain,
  AnticipatedObjection,
  DeckSlide,
  PreDeck,
  PreDeckSlide,
  ClientAttendee,
  InternalAttendee,
  ClientInteraction,
  InfluenceLevel,
  SentimentTrend,
  PlannedArtifact,
  ArtifactFulfillment,
  ContentToGenerate,
  PlannedArtifactType,
  ArtifactFulfillmentStatus,
  PreDcAgentStatus,
  RelevantDocument,
  RelevantProject,
  RelevantProjectSource,
  RelevantDocumentFormat,
} from "@dc-copilot/types/brief";
