/** Re-export brief shapes from shared types (no mock data). */
export type {
  CallBrief,
  PostCallReview,
  BriefResearchSection,
  PostDcBriefPreview,
  HypothesizedPain,
  AnticipatedObjection,
  DeckSlide,
  ClientAttendee,
  InternalAttendee,
  ClientInteraction,
  InfluenceLevel,
  SentimentTrend,
  PlannedArtifact,
  ArtifactFulfillment,
  PlannedArtifactType,
  ArtifactFulfillmentStatus,
  PreDcAgentStatus,
} from "@dc-copilot/types/brief";
